#ifndef INCLUDE_VERSION_H
#define INCLUDE_VERSION_H

#define MAJOR_VERSION    1
#define MINOR_VERSION    23
#define REVISION_VERSION 0
#define BUILD_VERSION    1000

#define VERSION MAJOR_VERSION,MINOR_VERSION,REVISION_VERSION,BUILD_VERSION   

#endif
