#ifndef YDWE_VERSION_H_INCLUDED
#define YDWE_VERSION_H_INCLUDED

#define YDWE_VERSION_MAJOR 1
#define YDWE_VERSION_MINOR 25
#define YDWE_VERSION_REVISED 3
#define YDWE_VERSION_BUILD 2003

#endif // YDWE_VERSION_H_INCLUDED
