
#define OperatorDegreeAdd(a,b)       ((a)+(b))
#define OperatorDegreeSubtract(a,b)  ((a)-(b))
#define OperatorDegreeMultiply(a,b)  ((a)*(b))
#define OperatorDegreeDivide(a,b)    ((a)/(b))
#define OperatorRadianAdd(a,b)       ((a)+(b))
#define OperatorRadianSubtract(a,b)  ((a)-(b))
#define OperatorRadianMultiply(a,b)  ((a)*(b))
#define OperatorRadianDivide(a,b)    ((a)/(b))
#define OperatorIntegerAdd(a,b)      ((a)+(b))
#define OperatorIntegerSubtract(a,b) ((a)-(b))
#define OperatorIntegerMultiply(a,b) ((a)*(b))
#define OperatorIntegerDivide(a,b)   ((a)/(b))
#define OperatorRealAdd(a,b)         ((a)+(b))
#define OperatorRealSubtract(a,b)    ((a)-(b))
#define OperatorRealMultiply(a,b)    ((a)*(b))
#define OperatorRealDivide(a,b)      ((a)/(b))

#define YDWEOperatorInt3(a1,op1,a2,op2,a3) ((a1)op1(a2)op2(a3))
#define YDWEOperatorReal3(a1,op1,a2,op2,a3) ((a1)op1(a2)op2(a3))
#define YDWEOperatorString3(a1,a2,a3) ((a1)+(a2)+(a3))

#define YDWER2Rad(a) (a)
#define YDWER2Deg(a) (a)
#define YDWEDeg2R(a) (a)
#define YDWERad2R(a) (a)

#define YDWEInitHashtable()           InitHashtable()
#define YDWEIsTriggerEventId(eventid) (eventid == GetTriggerEventId())

#define YDWEGetUnitID(a)             YDWEH2I(a)
#define YDWEGetItemID(a)             YDWEH2I(a)
#define YDWEGetPlayerID(a)           YDWEH2I(a)
#define YDWEGetTimerID(a)            YDWEH2I(a)
#define YDWEGetTriggerID(a)          YDWEH2I(a)
#define YDWEGetGroupID(a)            YDWEH2I(a)
#define YDWEGetLocationID(a)         YDWEH2I(a)
#define YDWEGetMultiboardID(a)       YDWEH2I(a)
#define YDWEGetMultiboardItemID(a)   YDWEH2I(a)
#define YDWEGetTextTagID(a)          YDWEH2I(a)
#define YDWEGetLightningID(a)        YDWEH2I(a)
#define YDWEGetRegionID(a)           YDWEH2I(a)
#define YDWEGetRectID(a)             YDWEH2I(a)
#define YDWEGetLeaderboardID(a)      YDWEH2I(a)
#define YDWEGetEffectID(a)           YDWEH2I(a)
#define YDWEGetDestructableID(a)     YDWEH2I(a)
#define YDWEGetTriggerConditionID(a) YDWEH2I(a)
#define YDWEGetTriggerActionID(a)    YDWEH2I(a)
#define YDWEGetTriggerEventID(a)     YDWEH2I(a)
#define YDWEGetForceID(a)            YDWEH2I(a)
#define YDWEGetBoolexprID(a)         YDWEH2I(a)
#define YDWEGetSoundID(a)            YDWEH2I(a)
#define YDWEGetTimerDialogID(a)      YDWEH2I(a)
#define YDWEGetTrackableID(a)        YDWEH2I(a)
#define YDWEGetDialogID(a)           YDWEH2I(a)
#define YDWEGetButtonID(a)           YDWEH2I(a)

#define YDWEConvert(a) (a)
#define YDWEGetUnitTypeID(a)         (a)
#define YDWEGetAbilityTypeID(a)      (a)
#define YDWEGetItemTypeID(a)         (a)
#define YDWEConverUnitcodeToInt(a)   (a)
#define YDWEConverItemcodeToInt(a)   (a)
#define YDWEConverAbilcodeToInt(a)   (a)
#define YDWEConverOrdercodeToInt(a)  (a)
#define YDWEUOrderId2OrderId(a)      (a)
#define YDWEPOrderId2OrderId(a)      (a)
#define YDWEDOrderId2OrderId(a)      (a)
#define YDWEIOrderId2OrderId(a)      (a)
#define YDWENOrderId2OrderId(a)      (a)
#define YDWEI2UnitId(a)              (a)
#define YDWEI2ItemId(a)              (a)

#define YDWECreateQuest(questType, title, description, iconPath) CreateQuestBJ(questType, title, description, iconPath)
#define YDWECreateQuestItem(whichQuest, description)             CreateQuestItemBJ(whichQuest, description)

#define YDWEAbilityId2OrderId(abilcode, type) <?=ability2order(#abilcode, (type))?>



