#include <string>
#include <map>

namespace locvar
{
	std::map<std::string, std::string> trigger_data_ui = {
		{ "GetTriggeringTrigger", "trigger" },
		{ "GetTriggerEventId", "eventid" },
		{ "GetEventGameState", "gamestate" },
		{ "GetWinningPlayer", "player" },
		{ "GetTriggeringRegion", "region" },
		{ "GetEnteringUnit", "unit" },
		{ "GetLeavingUnit", "unit" },
		{ "GetTriggeringTrackable", "trackable" },
		{ "GetClickedButton", "button" },
		{ "GetClickedDialog", "dialog" },
		{ "GetTournamentFinishSoonTimeRemaining", "real" },
		{ "GetTournamentFinishNowRule", "integer" },
		{ "GetTournamentFinishNowPlayer", "player" },
		{ "GetSaveBasicFilename", "string" },
		{ "GetTriggerPlayer", "player" },
		{ "GetLevelingUnit", "unit" },
		{ "GetLearningUnit", "unit" },
		{ "GetLearnedSkill", "integer" },
		{ "GetLearnedSkillLevel", "integer" },
		{ "GetRevivableUnit", "unit" },
		{ "GetRevivingUnit", "unit" },
		{ "GetAttacker", "unit" },
		{ "GetRescuer", "unit" },
		{ "GetDyingUnit", "unit" },
		{ "GetKillingUnit", "unit" },
		{ "GetDecayingUnit", "unit" },
		{ "GetConstructingStructure", "unit" },
		{ "GetCancelledStructure", "unit" },
		{ "GetConstructedStructure", "unit" },
		{ "GetResearchingUnit", "unit" },
		{ "GetResearched", "integer" },
		{ "GetTrainedUnitType", "integer" },
		{ "GetTrainedUnit", "unit" },
		{ "GetDetectedUnit", "unit" },
		{ "GetSummoningUnit", "unit" },
		{ "GetSummonedUnit", "unit" },
		{ "GetTransportUnit", "unit" },
		{ "GetLoadedUnit", "unit" },
		{ "GetSellingUnit", "unit" },
		{ "GetSoldUnit", "unit" },
		{ "GetBuyingUnit", "unit" },
		{ "GetSoldItem", "item" },
		{ "GetChangingUnit", "unit" },
		{ "GetChangingUnitPrevOwner", "player" },
		{ "GetManipulatingUnit", "unit" },
		{ "GetManipulatedItem", "item" },
		{ "GetOrderedUnit", "unit" },
		{ "GetIssuedOrderId", "integer" },
		{ "GetOrderPointX", "real" },
		{ "GetOrderPointY", "real" },
		{ "GetOrderPointLoc", "location" },
		{ "GetOrderTarget", "widget" },
		{ "GetOrderTargetDestructable", "destructable" },
		{ "GetOrderTargetItem", "item" },
		{ "GetOrderTargetUnit", "unit" },
		{ "GetSpellAbilityUnit", "unit" },
		{ "GetSpellAbilityId", "integer" },
		{ "GetSpellAbility", "ability" },
		{ "GetSpellTargetLoc", "location" },
		{ "GetSpellTargetDestructable", "destructable" },
		{ "GetSpellTargetItem", "item" },
		{ "GetSpellTargetUnit", "unit" },
		{ "GetEventPlayerState", "playerstate" },
		{ "GetEventPlayerChatString", "string" },
		{ "GetEventPlayerChatStringMatched", "string" },
		{ "GetTriggerUnit", "unit" },
		{ "GetEventUnitState", "unitstate" },
		{ "GetEventDamage", "real" },
		{ "GetEventDamageSource", "unit" },
		{ "GetEventDetectingPlayer", "player" },
		{ "GetEventTargetUnit", "unit" },
		{ "GetTriggerWidget", "widget" },
		{ "GetTriggerDestructable", "destructable" },
	};
}
