return {
    metadata = {
        ability = 'abilitymetadata.slk',
        destructable = 'destructablemetadata.slk',
        doodad = 'doodadmetadata.slk',
        buff = 'abilitybuffmetadata.slk',
        upgrade = 'upgrademetadata.slk',
        item = 'unitmetadata.slk',
        unit = 'unitmetadata.slk',
        misc = 'miscmetadata.slk',
    },
    obj = {
        ability = 'war3map.w3a',
        destructable = 'war3map.w3b',
        doodad = 'war3map.w3d',
        buff = 'war3map.w3h',
        upgrade = 'war3map.w3q',
        item = 'war3map.w3t',
        unit = 'war3map.w3u',
        misc = 'war3mapmisc.txt',
    },
    lni = {
        ability = 'ability.ini',
        destructable = 'destructable.ini',
        doodad = 'doodad.ini',
        buff = 'buff.ini',
        upgrade = 'upgrade.ini',
        item = 'item.ini',
        unit = 'unit.ini',
        misc = 'misc.ini',
    },
    slk = {
        ability = {'units\\abilitydata.slk'},
        destructable = {'units\\destructabledata.slk'},
        doodad = {'doodads\\doodads.slk'},
        buff = {'units\\abilitybuffdata.slk'},
        upgrade = {'units\\upgradedata.slk'},
        item = {'units\\itemdata.slk'},
        unit = {
            'units\\unitui.slk',
            'units\\unitdata.slk',
            'units\\unitbalance.slk',
            'units\\unitabilities.slk',
            'units\\unitweapons.slk',
        },
    },
    txt = {
        'units\\campaignunitstrings.txt',
        'units\\humanunitstrings.txt',
        'units\\neutralunitstrings.txt',
        'units\\nightelfunitstrings.txt',
        'units\\orcunitstrings.txt',
        'units\\undeadunitstrings.txt',
        'units\\campaignunitfunc.txt',
        'units\\humanunitfunc.txt',
        'units\\neutralunitfunc.txt',
        'units\\nightelfunitfunc.txt',
        'units\\orcunitfunc.txt',
        'units\\undeadunitfunc.txt',
        
        'units\\campaignabilitystrings.txt',
        'units\\commonabilitystrings.txt',
        'units\\humanabilitystrings.txt',
        'units\\neutralabilitystrings.txt',
        'units\\nightelfabilitystrings.txt',
        'units\\orcabilitystrings.txt',
        'units\\undeadabilitystrings.txt',
        'units\\itemabilitystrings.txt',
        'units\\campaignabilityfunc.txt',
        'units\\commonabilityfunc.txt',
        'units\\humanabilityfunc.txt',
        'units\\neutralabilityfunc.txt',
        'units\\nightelfabilityfunc.txt',
        'units\\orcabilityfunc.txt',
        'units\\undeadabilityfunc.txt',
        'units\\itemabilityfunc.txt',
        
        'units\\campaignupgradestrings.txt',
        'units\\neutralupgradestrings.txt',
        'units\\nightelfupgradestrings.txt',
        'units\\humanupgradestrings.txt',
        'units\\orcupgradestrings.txt',
        'units\\undeadupgradestrings.txt',
        'units\\campaignupgradefunc.txt',
        'units\\humanupgradefunc.txt',
        'units\\neutralupgradefunc.txt',
        'units\\nightelfupgradefunc.txt',
        'units\\orcupgradefunc.txt',
        'units\\undeadupgradefunc.txt',
        
        'units\\itemstrings.txt',
        'units\\itemfunc.txt',
    },
    misc = {
        'ui\\miscdata.txt',
        'units\\miscdata.txt',
        'units\\miscgame.txt',
    },
    key = {
        max_level = {
            ability = 'levels',
            doodad = 'numvar',
            upgrade = 'maxlevel',
        }
    },
    pack = {
        impignore = {
            'war3map.j',
            'war3map.doo',
            'war3map.imp',
            'war3map.mmp',
            'war3map.shd',
            'war3map.w3c',
            'war3map.w3e',
            'war3map.w3i',
            'war3map.w3r',
            'war3map.w3s',
            'war3map.wct',
            'war3map.wpm',
            'war3map.wtg',
            'war3map.wts',
            'war3mapextra.txt',
            'war3mapmap.blp',
            'war3mapmisc.txt',
            'war3mapskin.txt',
            'war3mapunits.doo',
            'war3map.txt.ini',
        },
        packignore = {
            '(attributes)',
            '(listfile)',
            '(signature)',
        }
    },
    lni_dir = {
        ability = {'table\\ability.ini', 'war3map.w3a.ini'},
        destructable = {'table\\destructable.ini', 'war3map.w3b.ini'},
        doodad = {'table\\doodad.ini', 'war3map.w3d.ini'},
        buff = {'table\\buff.ini', 'war3map.w3h.ini'},
        upgrade = {'table\\upgrade.ini', 'war3map.w3q.ini'},
        item = {'table\\item.ini', 'war3map.w3t.ini'},
        unit = {'table\\unit.ini', 'war3map.w3u.ini'},
        misc = {'table\\misc.ini'},
        w3i = {'table\\w3i.ini', 'war3map.w3i.ini'},
        txt = {'table\\txt.ini', 'war3map.txt.ini'},
        imp = {'table\\imp.ini', 'war3map.imp.ini'},
        doo = {'table\\doo.ini', 'war3map.doo.ini'},
    }
}
